### ISSUE TITLE
Licence? 

### ISSUE THREAD

**Issue by cadet-blue-git** [grasskode/browserstack-api#1]
Does this project have a license?

**Comment by grasskode** [comment]
It was just an exercise for a company I was interviewing. There is a license now though. :)

**Comment by cadet-blue-git** [comment]
Great thanks :) This really helped me out. 

And can I have confirmation that it would be acceptable to use this software prior to the addition of this license?

**Comment by grasskode** [comment]
Yes it is perfectly acceptable. :)

Though I must add the disclaimer that I do not hold any right to any information that is particular to [browserstack](https://www.browserstack.com/). For any piece of code that might help you, you are free to use it as per the MIT License which is now added.

**Comment by cadet-blue-git** [comment]
Excellent. Thanks :+1:
